// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUEFNsfnUxnneuy-JuhyUMXsmGZRu1jHE',
    appId: '1:109249628543:web:8ec9d6c60ff34e512d324a',
    messagingSenderId: '109249628543',
    projectId: 'quickexit-a4191',
    authDomain: 'quickexit-a4191.firebaseapp.com',
    storageBucket: 'quickexit-a4191.appspot.com',
    measurementId: 'G-NTPDTF66YW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY3UyvkD25E_Wq_I9qcFZyMYFNLPo-CiU',
    appId: '1:109249628543:android:d234165738bb94ac2d324a',
    messagingSenderId: '109249628543',
    projectId: 'quickexit-a4191',
    storageBucket: 'quickexit-a4191.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBYgxbNwJuYRUF7Gh-F3r7uM8g0B2XaOo',
    appId: '1:109249628543:ios:a2478a627f906fba2d324a',
    messagingSenderId: '109249628543',
    projectId: 'quickexit-a4191',
    storageBucket: 'quickexit-a4191.appspot.com',
    iosBundleId: 'com.example.quickExit',
  );

}